export const proposals = [
  {
    id: "1",
    author: "wombat.eth",
    title: "vote on new strategy",
    summary: "brief summary",
    abstract: "long text",
    status: "active",
    createdAt: "29/09/20222",
    endsAt: "29/12/20222",
    voted: true,
    totalVotes: 3,
  },
  {
    id: "2",
    author: "janineleger.eth",
    title: "Accept a new member",
    summary: "brief summary",
    abstract: "long text",
    status: "active",
    createdAt: "12/08/20222",
    endsAt: "02/12/20222",
    voted: false,
    totalVotes: 2,
  },
  {
    id: "3",
    author: "janineleger.eth",
    title: "Propose a new strategy",
    summary: "brief summary",
    abstract: "long text",
    status: "closed",
    createdAt: "12/06/20222",
    endsAt: "30/11/20222",
    voted: true,
    totalVotes: 5,
  },
];
